export const START_FETCHING_PROJECT = 'redux/article/START_FETCHING_PROJECT'
export const SUCCESS_FETCHING_PROJECT = 'redux/article/SUCCESS_FETCHING_PROJECT'
export const ERROR_FETCHING_PROJECT = 'redux/article/ERROR_FETCHING_PROJECT'

export const START_FETCHING_ONE_PROJECT = 'redux/article/START_FETCHING_ONE_PROJECT'
export const SUCCESS_FETCHING_ONE_PROJECT = 'redux/article/SUCCESS_FETCHING_ONE_PROJECT'
export const ERROR_FETCHING_ONE_PROJECT = 'redux/article/ERROR_FETCHING_ONE_PROJECT'