export const START_FETCHING_ARTICEL = 'redux/article/START_FETCHING_ARTICEL'
export const SUCCESS_FETCHING_ARTICEL = 'redux/article/SUCCESS_FETCHING_ARTICEL'
export const ERROR_FETCHING_ARTICEL = 'redux/article/ERROR_FETCHING_ARTICEL'

export const START_FETCHING_ONE_ARTIKEL = 'redux/article/START_FETCHING_ONE_ARTIKEL'
export const SUCCESS_FETCHING_ONE_ARTIKEL = 'redux/article/SUCCESS_FETCHING_ONE_ARTIKEL'
export const ERROR_FETCHING_ONE_ARTIKEL = 'redux/article/ERROR_FETCHING_ONE_ARTIKEL'